logging:
  level: "INFO"
  logfile: "./scraperlog"

embeddings:
  type: "HUGGING_FACE_GTE_BASE"

site:
  url: "https://www.orlando.gov"
  sitemap: "/sitemap.xml"
  name: "city_orlando"
  scraped-path: "./scraped/"
  use-vector-db: True

openai:
  key: "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"

vectordb:
  chroma-path: "./chroma_clean"