openai:
  key: "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"

kbs:
-
  name: "chroma"
  directory: "../chroma"
  embeddings: "OPEN_AI"
-
  name: "chroma_cheap"
  directory: "../chroma_cheap"
  embeddings: "OPEN_AI"
-
  name: "chroma_clean_ada"
  directory: "../chroma_clean_ada"
  embeddings: "OPEN_AI"

azure:
    endpoint: "https://sondertest.openai.azure.com/"
    version: "2023-07-01-preview"
    type: "azure"
